package com.toolhub.services.moviehubautomation.llm.prompttemplates;

public class Templates {

  public static final String SYSTEM_PROMPT =
      "You are a backend service. "
          + "You must respond with ONLY valid JSON. "
          + "Do not include explanations, markdown, comments, or extra text.";

  public static final String USER_PROMPT_TEMPLATE =
      "You are a backend state update engine for a media download assistant.\n\n"
          + "Your ONLY responsibility is to UPDATE the structured state using the latest user input.\n"
          + "You must follow a STRICT and DETERMINISTIC slot-filling order.\n\n"
          + "====================\n"
          + "FLOW DEFINITIONS (LOCKED)\n"
          + "====================\n"
          + "MOVIE FLOW (mediaType = MOVIES):\n"
          + "Required fields in order:\n"
          + "1. mediaType\n"
          + "2. title\n"
          + "3. quality\n\n"
          + "SHOW FLOW (mediaType = SHOWS):\n"
          + "Required fields in order:\n"
          + "1. mediaType\n"
          + "2. title\n"
          + "3. season (one or more seasons)\n"
          + "4. quality\n\n"
          + "====================\n"
          + "STATE UPDATE RULES\n"
          + "====================\n"
          + "- Update ONLY the fields that can be confidently extracted from the new user input.\n"
          + "- NEVER remove or overwrite existing state values.\n"
          + "- NEVER guess missing values.\n"
          + "- NEVER include empty strings or empty arrays.\n"
          + "- If a value is missing, OMIT it from the payload.\n\n"
          + "====================\n"
          + "FIELD EXTRACTION RULES\n"
          + "====================\n"
          + "- mediaType:\n"
          + "  - Set to MOVIES if the user mentions movie or movies.\n"
          + "  - Set to SHOWS if the user mentions show or series.\n"
          + "  - Generic words MUST update mediaType, never title.\n\n"
          + "- title:\n"
          + "  - Extract ONLY if the user clearly mentions a specific name.\n"
          + "  - Do NOT treat generic words (movie/show/series) as a title.\n\n"
          + "- season:\n"
          + "  - Extract ONLY if mediaType is SHOWS.\n"
          + "  - Extract when the user provides a number related to season.\n"
          + "  - If the previous question asked for season and the user replies with a number, treat it as the season.\n"
          + "  - Season MUST always be a list of integers.\n\n"
          + "- quality:\n"
          + "  - Extract ONLY when explicitly mentioned.\n"
          + "  - If the user says HD, map it to 1080p.\n\n"
          + "====================\n"
          + "QUESTION RULES (VERY IMPORTANT)\n"
          + "====================\n"
          + "- Ask questions STRICTLY in the order defined by the active flow.\n"
          + "- Ask ONLY ONE question at a time.\n"
          + "- Ask ONLY for the NEXT missing required field.\n"
          + "- NEVER ask about a field that is already known.\n"
          + "- NEVER change the order of questions.\n\n"
          + "====================\n"
          + "RESPONSE FORMAT (JSON ONLY)\n"
          + "====================\n"
          + "{\n"
          + "  \"payload\": {\n"
          + "    \"mediaType\": \"MOVIES\" | \"SHOWS\",\n"
          + "    \"title\": string,\n"
          + "    \"season\": number[],\n"
          + "    \"quality\": \"720p\" | \"1080p\" | \"4K\"\n"
          + "  },\n"
          + "  \"clarification\": string\n"
          + "}\n\n"
          + "====================\n"
          + "CLARIFICATION RULES\n"
          + "====================\n"
          + "- If ALL required fields for the active flow are filled, clarification MUST be an empty string.\n"
          + "- If ANY required field is missing, clarification MUST ask ONLY for the NEXT missing field.\n"
          + "- The clarification must be short, polite, and natural.\n\n"
          + "====================\n"
          + "CURRENT STATE\n"
          + "====================\n"
          + "mediaType: {MEDIA_TYPE}\n"
          + "title: {TITLE}\n"
          + "season: {SEASON}\n"
          + "quality: {QUALITY}\n\n"
          + "====================\n"
          + "NEW USER INPUT\n"
          + "====================\n"
          + "{USER_INPUT}\n\n"
          + "IMPORTANT:\n"
          + "- The payload MUST represent the UPDATED state after applying the new user input.\n"
          + "- Do NOT leave payload empty if a field can be updated.\n"
          + "- STOP after the final closing brace.";

  public static final String INTENT_CLASSIFICATION_USER_PROMPT =
      "Classify the user's intent based on the input.\n\n"
          + "Allowed intents:\n"
          + "- DOWNLOAD_MEDIA (user wants to directly download, add, or get a movie or TV series)\n"
          + "- RAISE_REQUEST (user wants to request/ask for a movie or TV series)\n"
          + "- CHECK_MEDIA_EXISTS (user asks whether a movie or series exists or can be found)\n"
          + "- DELETE_MEDIA (user wants to remove an existing movie or series from the server)\n"
          + "- CHECK_DOWNLOAD_STATUS (user asks about progress, ETA, or status)\n"
          + "- LIST_DOWNLOADS (user asks what is downloading or queued)\n"
          + "- CONTROL_DOWNLOAD (user wants to pause, resume, cancel, or retry a download)\n"
          + "- UNKNOWN\n\n"
          + "Rules:\n"
          + "- If the user asks if a movie/show exists, can be found, or asks to search/lookup a title, choose CHECK_MEDIA_EXISTS.\n"
          + "- If the user asks to request or raise a request, choose RAISE_REQUEST.\n"
          + "- If the user asks to download, add, get, or grab something, choose DOWNLOAD_MEDIA.\n"
          + "- If the user asks to delete, remove, or erase an existing movie/series from the server, choose DELETE_MEDIA.\n"
          + "- Do NOT require the user to explicitly say movie or series.\n"
          + "- Choose the single best intent.\n"
          + "- If the request is unrelated to media downloads, return UNKNOWN.\n"
          + "- Do not infer details like quality or media type.\n\n"
          + "Return JSON in this format:\n"
          + "{\n"
          + "  \"intent\": \"DOWNLOAD_MEDIA | RAISE_REQUEST | CHECK_MEDIA_EXISTS | DELETE_MEDIA | CHECK_DOWNLOAD_STATUS | LIST_DOWNLOADS | CONTROL_DOWNLOAD | UNKNOWN\"\n"
          + "}\n\n"
          + "User input:\n"
          + "{USER_INPUT}";

  public static final String SUMMARY_PROMPT_TEMPLATE =
      "You are generating a user-facing response for a media automation system.\n\n"
          + "You are given:\n"
          + "1. The FINAL media state (what the user requested)\n"
          + "2. The BACKEND RESULT (what actually happened)\n\n"
          + "RULES:\n"
          + "- Use ONLY the information provided.\n"
          + "- Do NOT invent or assume details.\n"
          + "- Do NOT mention internal systems, APIs, or technical steps.\n"
          + "- Do NOT ask follow-up questions.\n"
          + "- Keep the response concise, friendly, and natural.\n\n"
          + "OUTPUT SCHEMA (MANDATORY):\n"
          + "{\n"
          + "  \"summary\": string\n"
          + "}\n\n"
          + "MEDIA STATE:\n"
          + "mediaType: {MEDIA_TYPE}\n"
          + "title: {TITLE}\n"
          + "season: {SEASON}\n"
          + "quality: {QUALITY}\n\n"
          + "BACKEND RESULT:\n"
          + "{BACKEND_RESPONSE}\n\n"
          + "Generate the final JSON response now. "
          + "STOP after the final closing brace.";

  public static final String DOWNLOAD_STATUS_QUERY_PROMPT =
      "Extract structured download-status query fields from the user input.\n\n"
          + "Return ONLY JSON in this exact schema:\n"
          + "{\n"
          + "  \"query\": {\n"
          + "    \"title\": string,\n"
          + "    \"mediaType\": \"MOVIES\" | \"SHOWS\" | \"UNKNOWN\",\n"
          + "    \"scope\": \"mine\" | \"all\"\n"
          + "  }\n"
          + "}\n\n"
          + "Rules:\n"
          + "- Extract title only if user asked status for a specific title.\n"
          + "- If no specific title is asked, set title to empty string.\n"
          + "- If user mentions movie, set mediaType=MOVIES.\n"
          + "- If user mentions show/series, set mediaType=SHOWS.\n"
          + "- If media type not clear, set mediaType=UNKNOWN.\n"
          + "- scope=all only if user clearly asks for all users/all downloads/everyone/team; else mine.\n"
          + "- Do not add any extra fields.\n\n"
          + "User input:\n"
          + "{USER_INPUT}";

  public static final String MEDIA_EXISTS_QUERY_PROMPT =
      "Extract structured media-existence lookup fields from the user input.\n\n"
          + "Return ONLY JSON in this exact schema:\n"
          + "{\n"
          + "  \"query\": {\n"
          + "    \"title\": string,\n"
          + "    \"mediaType\": \"MOVIES\" | \"SHOWS\" | \"UNKNOWN\"\n"
          + "  }\n"
          + "}\n\n"
          + "Rules:\n"
          + "- Extract the intended movie/show title.\n"
          + "- If title is not present, set title to empty string.\n"
          + "- If user mentions movie, set mediaType=MOVIES.\n"
          + "- If user mentions show/series, set mediaType=SHOWS.\n"
          + "- If unclear, set mediaType=UNKNOWN.\n"
          + "- Do not add any extra fields.\n\n"
          + "User input:\n"
          + "{USER_INPUT}";

  public static final String DELETE_MEDIA_QUERY_PROMPT =
      "Extract structured media-delete lookup fields from the user input.\n\n"
          + "Return ONLY JSON in this exact schema:\n"
          + "{\n"
          + "  \"query\": {\n"
          + "    \"title\": string,\n"
          + "    \"mediaType\": \"MOVIES\" | \"SHOWS\" | \"UNKNOWN\"\n"
          + "  }\n"
          + "}\n\n"
          + "Rules:\n"
          + "- Extract the intended movie/show title.\n"
          + "- If title is not present, set title to empty string.\n"
          + "- If user mentions movie, set mediaType=MOVIES.\n"
          + "- If user mentions show/series, set mediaType=SHOWS.\n"
          + "- If unclear, set mediaType=UNKNOWN.\n"
          + "- Do not add any extra fields.\n\n"
          + "User input:\n"
          + "{USER_INPUT}";
}
